# SPDX-FileCopyrightText: 2026 SombrAbsol
#
# SPDX-License-Identifier: MIT

name: Build latest change

on:
  push:
    branches: [ "main" ]
    paths:
      - "src/**"
      - "include/**"
      - "Makefile"
  pull_request:
    branches: [ "main" ]
    paths:
      - "src/**"
      - "include/**"
      - "Makefile"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-26, windows-2025]
        target: [ra2mes, ra3mes]
        include:
          - os: ubuntu-24.04
            artifact-suffix: linux
            extension: ""

          - os: macos-26
            artifact-suffix: macos
            extension: ""

          - os: windows-2025
            artifact-suffix: windows
            extension: .exe

    name: Build ${{ matrix.target }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Build ${{ matrix.target }}
        run: make CC=clang ${{ matrix.target }}

      - name: Upload ${{ matrix.target }} artefact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.target }}-${{ matrix.artifact-suffix }}
          path: |
            build/${{ matrix.target }}${{ matrix.extension }}
            LICENSE
          if-no-files-found: error
